// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65h1OatpqglpFL8DWpjkWotFYxG5Cr0c',
    appId: '1:927230512965:web:700c92c726a42c6745382c',
    messagingSenderId: '927230512965',
    projectId: 'carbonfootfrinters',
    authDomain: 'carbonfootfrinters.firebaseapp.com',
    storageBucket: 'carbonfootfrinters.firebasestorage.app',
    measurementId: 'G-M4MZ2F7BFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33z9Q8fvT4yYTu3R2znP58ZV3MINvQyY',
    appId: '1:927230512965:android:6707b89b004e677045382c',
    messagingSenderId: '927230512965',
    projectId: 'carbonfootfrinters',
    storageBucket: 'carbonfootfrinters.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0CL3JbaJthAZ4g2eY8W4ZTBL7MykxEM',
    appId: '1:927230512965:ios:ea9787c30d39275445382c',
    messagingSenderId: '927230512965',
    projectId: 'carbonfootfrinters',
    storageBucket: 'carbonfootfrinters.firebasestorage.app',
    iosClientId: '927230512965-qqm74fciu5p2tcnhv8lh5o0cadud8o1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonFootPrinter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0CL3JbaJthAZ4g2eY8W4ZTBL7MykxEM',
    appId: '1:927230512965:ios:ea9787c30d39275445382c',
    messagingSenderId: '927230512965',
    projectId: 'carbonfootfrinters',
    storageBucket: 'carbonfootfrinters.firebasestorage.app',
    iosClientId: '927230512965-qqm74fciu5p2tcnhv8lh5o0cadud8o1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonFootPrinter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC65h1OatpqglpFL8DWpjkWotFYxG5Cr0c',
    appId: '1:927230512965:web:4c763e2b1539b4c545382c',
    messagingSenderId: '927230512965',
    projectId: 'carbonfootfrinters',
    authDomain: 'carbonfootfrinters.firebaseapp.com',
    storageBucket: 'carbonfootfrinters.firebasestorage.app',
    measurementId: 'G-R1WGSJT3NQ',
  );
}
